### ISSUE TITLE
[OMEMO] Protected MUC Room problem, if alone -> OMEMO is forcing: *** [OMEMO] Unable to build any sessions, the message was not sent

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/plugins#57]
When we are on a protected MUC Room, after an OMEMO discussion with several people, if we are the last people (alone):
- OMEMO icon: Grey "OMEMO is not available for this contact"

When we send a message:
- *** [OMEMO] Unable to build any sessions, the message was not sent

-> Impossible to disable OMEMO (icon is in grey)

Linked to:
- https://github.com/psi-im/plugins/issues/54
- https://github.com/psi-im/plugins/issues/49

**Comment by tehnick** [comment]
Try Psi+ 1.4.1299 or newer please.

**Comment by Neustradamus** [comment]
@kssytsrk: Can you look this ticket?

**Comment by kssytsrk** [comment]
Can reproduce on Psi+ 1.5.1551 (2021-08-16) / FreeBSD 13.0, but isn't this expected behavior? I don't think it'd be troublesome to implement OMEMO-encrypting the message using sender's own key, just not sure if it's needed/conforming to the XEP ([here](https://xmpp.org/extensions/xep-0384.html), for example, it is specified that the messages should be encrypted using the recipients' keys and the keys of sender's other devices). Have you tested this with any other clients (Gajim, Dino, Conversations?), do they implement this?

**Comment by Neustradamus** [comment]
I have done a new ticket, now we are not "OMEMO forced" with last commits from @nullobsi and @stigger (thanks) but the problem is always here when the last try to send an OMEMO message in MUC Room (and the error is now showed for myself OMEMO messages that were not showed before, invisible).

Linked to:
- https://github.com/psi-im/plugins/issues/49
- https://github.com/psi-im/plugins/issues/114
