### ISSUE TITLE
[OMEMO] Show fingerprint of other devices

### ISSUE THREAD

**Issue by cweiske** [psi-im/plugins#60]
The "Mange devices" list only shows device IDs and no fingerprints.

Neither Conversations nor Dino show their device ID - only their fingerprint.
So it is currently impossible to verify the other devices and remove invalid ones.

![2020-02-11 psi omemo manage devices](https://user-images.githubusercontent.com/59036/74219328-cfa4ee80-4cac-11ea-80d2-35264f7ad42b.png)

**Comment by tehnick** [comment]
06259e6b41ede7b2f8485adf6eb38bf443be860a

**Comment by tehnick** [comment]
BTW, Gajim shows devices IDs.

**Comment by tehnick** [comment]
And have in mind that in according to XEP only devices IDs are guaranteed to be known:
https://xmpp.org/extensions/xep-0384.html#usecases-announcing

And unfortunately any client from users in my contact list does not send `label` info about device, because this is only **recommended** attribute... =(

**Comment by Neustradamus** [comment]
Time to update the XEP!
