### ISSUE TITLE
[OpenPGP] [Windows] Fix diagnostic output of GnuPG

### ISSUE THREAD

**Issue by tehnick** [psi-im/plugins#79]
https://github.com/psi-im/psi/issues/556#issuecomment-633229723

- Psi -> Options -> Plugins -> Settings of OpenPGP -> Keys Manager -> Diagnostics
- Psi -> Options -> Plugins -> Settings of OpenPGP -> Own Keys -> Select Key... -> Diagnostics

Screenshot:
- https://i.ibb.co/kJf99nV/psi-openpgp-gnupg-info.png

**Comment by tehnick** [comment]
Try Psi+ 1.4.1303 please.

**Comment by Neustradamus** [comment]
Always here! :/

It is that several languages have a space before ":"
- Test :
instead of
- Test:

Same for "!" "?" ";":
- Test !
instead of
- Test!

It is important to use located languages for all GnuPG parts?

Maybe the problem is in directly in GnuPG...

Maybe good to look and maybe report it...

**Comment by tehnick** [comment]
a4918661c1d6d12aeabd2afabc1196f692670555

**Comment by Neustradamus** [comment]
Tehnick: Thanks!
It solves this https://github.com/psi-im/psi/issues/556 too?

**Comment by Neustradamus3** [comment]
@tehnick: Thanks!
It solves this ticket too?
- https://github.com/psi-im/psi/issues/556

Same bad character for:
- Key Storage Diagnostic Text window
